module.exports = {
  apps: [
    {
      name: 'bot-petani',
      script: './bots/bot-petani.js',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 10000, // 10 detik sebelum restart
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      out_file: './logs/petani-out.log',
      error_file: './logs/petani-err.log',
    },
    {
      name: 'bot-penebang',
      script: './bots/bot-penebang.js',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 10000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      out_file: './logs/penebang-out.log',
      error_file: './logs/penebang-err.log',
    },
    {
      name: 'bot-penambang',
      script: './bots/bot-penambang.js',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 10000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      out_file: './logs/penambang-out.log',
      error_file: './logs/penambang-err.log',
    },
    {
      name: 'bot-penjaga',
      script: './bots/bot-penjaga.js',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 10000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      out_file: './logs/penjaga-out.log',
      error_file: './logs/penjaga-err.log',
    },
    {
      name: 'bot-builder',
      script: './bots/bot-builder.js',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 10000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      out_file: './logs/builder-out.log',
      error_file: './logs/builder-err.log',
    },
  ],
};
